"""empty message

Revision ID: 7b903580a884
Revises: 85e284240b45
Create Date: 2019-06-05 00:05:42.174949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b903580a884'
down_revision = '85e284240b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hot_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hot_score')
    # ### end Alembic commands ###
