"""empty message

Revision ID: 83820909682d
Revises: 63bd61926e9f
Create Date: 2019-04-18 19:04:55.653551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83820909682d'
down_revision = '63bd61926e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('read_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'read_count')
    # ### end Alembic commands ###
