"""empty message

Revision ID: 85e284240b45
Revises: b71e76cc9d25
Create Date: 2019-05-22 14:56:27.209672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e284240b45'
down_revision = 'b71e76cc9d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'is_active')
    # ### end Alembic commands ###
