"""empty message

Revision ID: 9e01abf146ef
Revises: d86fe2a721ab
Create Date: 2019-06-06 22:57:36.618987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e01abf146ef'
down_revision = 'd86fe2a721ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summarys', sa.Text(), nullable=False))
    op.drop_column('post', 'summary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('summary', mysql.TEXT(), nullable=False))
    op.drop_column('post', 'summarys')
    # ### end Alembic commands ###
