"""empty message

Revision ID: b71e76cc9d25
Revises: 83820909682d
Create Date: 2019-04-19 16:36:31.176250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b71e76cc9d25'
down_revision = '83820909682d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatars', sa.String(length=200), nullable=True))
    op.drop_column('front_user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('avatar', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('front_user', 'avatars')
    # ### end Alembic commands ###
